In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
from sklearn.metrics import make_scorer
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor

%matplotlib inline

In [2]:
df = pd.read_csv('data/TMDB_tv_dataset_v3.csv')

In [3]:
df.head()

,id,name,number_of_seasons,number_of_episodes,original_language,vote_count,vote_average,overview,adult,backdrop_path,...,tagline,genres,created_by,languages,networks,origin_country,spoken_languages,production_companies,production_countries,episode_run_time
0,1399,Game of Thrones,8,73,en,21857,8.442,Seven noble families fight for control of the ...,False,/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg,...,Winter Is Coming,"Sci-Fi & Fantasy, Drama, Action & Adventure","David Benioff, D.B. Weiss",en,HBO,US,English,"Revolution Sun Studios, Television 360, Genera...","United Kingdom, United States of America",0
1,71446,Money Heist,3,41,es,17836,8.257,"To carry out the biggest heist in history, a m...",False,/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg,...,The perfect robbery.,"Crime, Drama",Álex Pina,es,"Netflix, Antena 3",ES,Español,Vancouver Media,Spain,70
2,66732,Stranger Things,4,34,en,16161,8.624,"When a young boy vanishes, a small town uncove...",False,/2MaumbgBlW1NoPo3ZJO38A6v7OS.jpg,...,Every ending has a beginning.,"Drama, Sci-Fi & Fantasy, Mystery","Matt Duffer, Ross Duffer",en,Netflix,US,English,"21 Laps Entertainment, Monkey Massacre Product...",United States of America,0
3,1402,The Walking Dead,11,177,en,15432,8.121,Sheriff's deputy Rick Grimes awakens from a co...,False,/x4salpjB11umlUOltfNvSSrjSXm.jpg,...,Fight the dead. Fear the living.,"Action & Adventure, Drama, Sci-Fi & Fantasy",Frank Darabont,en,AMC,US,English,"AMC Studios, Circle of Confusion, Valhalla Mot...",United States of America,42
4,63174,Lucifer,6,93,en,13870,8.486,"Bored and unhappy as the Lord of Hell, Lucifer...",False,/aDBRtunw49UF4XmqfyNuD9nlYIu.jpg,...,It's good to be bad.,"Crime, Sci-Fi & Fantasy",Tom Kapinos,en,"FOX, Netflix",US,English,"Warner Bros. Television, DC Entertainment, Jer...",United States of America,45

In [4]:
df.isna().sum()

id                           0
name                         5
number_of_seasons            0
number_of_episodes           0
original_language            0
vote_count                   0
vote_average                 0
overview                 69485
adult                        0
backdrop_path            84597
first_air_date           30072
last_air_date            28041
homepage                109564
in_production                0
original_name                5
popularity                   0
poster_path              56513
type                         0
status                       0
tagline                 153794
genres                   64289
created_by              124095
languages                53791
networks                 64841
origin_country           31014
spoken_languages         54502
production_companies    102297
production_countries     85258
episode_run_time             0
dtype: int64

In [6]:
df2= df.groupby('original_language')

In [8]:
df2.head()

,id,name,number_of_seasons,number_of_episodes,original_language,vote_count,vote_average,overview,adult,backdrop_path,...,tagline,genres,created_by,languages,networks,origin_country,spoken_languages,production_companies,production_countries,episode_run_time
0,1399,Game of Thrones,8,73,en,21857,8.442,Seven noble families fight for control of the ...,False,/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg,...,Winter Is Coming,"Sci-Fi & Fantasy, Drama, Action & Adventure","David Benioff, D.B. Weiss",en,HBO,US,English,"Revolution Sun Studios, Television 360, Genera...","United Kingdom, United States of America",0
1,71446,Money Heist,3,41,es,17836,8.257,"To carry out the biggest heist in history, a m...",False,/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg,...,The perfect robbery.,"Crime, Drama",Álex Pina,es,"Netflix, Antena 3",ES,Español,Vancouver Media,Spain,70
2,66732,Stranger Things,4,34,en,16161,8.624,"When a young boy vanishes, a small town uncove...",False,/2MaumbgBlW1NoPo3ZJO38A6v7OS.jpg,...,Every ending has a beginning.,"Drama, Sci-Fi & Fantasy, Mystery","Matt Duffer, Ross Duffer",en,Netflix,US,English,"21 Laps Entertainment, Monkey Massacre Product...",United States of America,0
3,1402,The Walking Dead,11,177,en,15432,8.121,Sheriff's deputy Rick Grimes awakens from a co...,False,/x4salpjB11umlUOltfNvSSrjSXm.jpg,...,Fight the dead. Fear the living.,"Action & Adventure, Drama, Sci-Fi & Fantasy",Frank Darabont,en,AMC,US,English,"AMC Studios, Circle of Confusion, Valhalla Mot...",United States of America,42
4,63174,Lucifer,6,93,en,13870,8.486,"Bored and unhappy as the Lord of Hell, Lucifer...",False,/aDBRtunw49UF4XmqfyNuD9nlYIu.jpg,...,It's good to be bad.,"Crime, Sci-Fi & Fantasy",Tom Kapinos,en,"FOX, Netflix",US,English,"Warner Bros. Television, DC Entertainment, Jer...",United States of America,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152806,106080,حنين,1,10,av,0,0.000,NaN,False,/9Gk7q2f2ZNDvXvNtIaRbljt4IX5.jpg,...,NaN,Drama,NaN,av,Jawwy TV,SA,NaN,Jawwy TV,Saudi Arabia,0
153631,31126,Ruos Cheat Jivit,0,0,km,0,0.000,Ruos Chea Jivit is the first-ever Khmer film t...,False,NaN,...,NaN,NaN,NaN,km,NaN,NaN,NaN,NaN,NaN,0
155699,122868,The Croft,2,12,gd,0,0.000,Documentary following Donald MacSween as he tr...,False,NaN,...,NaN,Documentary,NaN,"en, gd",NaN,GB,English,NaN,United Kingdom,0
158034,107228,Las Santísimas,1,1,la,0,0.000,Five close friends will make us live different...,False,/1TMS8iDozeoCIZmpZIlfShJSSzG.jpg,...,NaN,NaN,Luis Felipe Salamanca,la,NaN,CO,Latin,Teleset,Colombia,45
158797,66881,Xal Maan U Waayey,1,18,so,0,0.000,NaN,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [9]:
unique = df[['original_language', 'languages']].drop_duplicates()

In [10]:
unique

       original_language   languages
0                     en          en
1                     es          es
6                     ko  en, ko, ur
7                     en  en, de, es
24                    ja          ja
...                  ...         ...
158612                fr          ko
158797                so         NaN
158843                fi          sv
158989                da  da, en, uk
158996                ms      ms, en

[1701 rows x 2 columns]

In [22]:
df2=unique.groupby('original_language').agg({'languages': 'first'})

In [23]:
df2

                  languages
original_language
aa                     None
ab                       ja
af                       af
am                       am
ar                       ar
...                     ...
vi                       vi
xx                       xx
za                       zh
zh                       zh
zu                       en

[106 rows x 1 columns]